import type {
  IntakeDraft,
  OrderRecord,
} from "@/components/orders/order-types"

export const mockOrders: OrderRecord[] = [
  {
    id: "ORD-1042",
    clientName: "Sri Balaji Traders",
    loadType: "Mangoes",
    origin: "Hyderabad",
    destination: "Visakhapatnam",
    truckCount: 4,
    assignedTruckCount: 2,
    reportingAt: "May 04, 8:00 AM",
    deliveryDeadline: "May 05, 6:00 PM",
    baseAmount: 180000,
    chargeableExtras: 12000,
    advancePaid: 50000,
    expectedBalance: 142000,
    invoiceStatus: "Ready for invoice",
    assignmentStatus: "Partially assigned",
    orderStatus: "Partially assigned",
    createdAt: "2026-05-03T10:30:00",
    source: "Direct",
    notes: "Client requested all trucks before lunch. Provider payment due after loading confirmation.",
    trips: [
      {
        id: "TRP-4201",
        orderId: "ORD-1042",
        truckType: "Own truck",
        truckNumberOrContact: "TS15UC2297",
        expectedArrivalAt: "May 05, 4:30 PM",
        expenseStatus: "Diesel recorded",
        providerDueStatus: "No provider due",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Arrival planned",
      },
      {
        id: "TRP-4202",
        orderId: "ORD-1042",
        truckType: "Outsourced truck",
        truckNumberOrContact: "Ravi Transport - AP29LB9592",
        expectedArrivalAt: "May 05, 5:00 PM",
        expenseStatus: "Outsourced cost tracked",
        providerDueStatus: "Rs 28,000 due",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Assigned",
      },
      {
        id: "TRP-4203",
        orderId: "ORD-1042",
        truckType: "Unassigned",
        truckNumberOrContact: "Needs truck",
        expectedArrivalAt: "May 05, 6:00 PM",
        expenseStatus: "No expense",
        providerDueStatus: "No provider selected",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Needs truck",
      },
      {
        id: "TRP-4204",
        orderId: "ORD-1042",
        truckType: "Unassigned",
        truckNumberOrContact: "Needs truck",
        expectedArrivalAt: "May 05, 6:00 PM",
        expenseStatus: "No expense",
        providerDueStatus: "No provider selected",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Needs truck",
      },
    ],
  },
  {
    id: "ORD-1038",
    clientName: "Kaveri Foods",
    loadType: "Bananas",
    origin: "Medchal",
    destination: "Vijayawada",
    truckCount: 2,
    assignedTruckCount: 0,
    reportingAt: "May 04, 11:30 AM",
    deliveryDeadline: "May 05, 9:00 AM",
    baseAmount: 78000,
    chargeableExtras: 5000,
    advancePaid: 0,
    expectedBalance: 83000,
    invoiceStatus: "Not invoiced",
    assignmentStatus: "Needs truck assignment",
    orderStatus: "Needs truck assignment",
    createdAt: "2026-05-02T16:20:00",
    source: "Quick Order",
    trips: [
      {
        id: "TRP-4188",
        orderId: "ORD-1038",
        truckType: "Unassigned",
        truckNumberOrContact: "Needs truck",
        expectedArrivalAt: "May 05, 8:00 AM",
        expenseStatus: "No expense",
        providerDueStatus: "No provider selected",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Needs truck",
      },
      {
        id: "TRP-4189",
        orderId: "ORD-1038",
        truckType: "Unassigned",
        truckNumberOrContact: "Needs truck",
        expectedArrivalAt: "May 05, 8:30 AM",
        expenseStatus: "No expense",
        providerDueStatus: "No provider selected",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Needs truck",
      },
    ],
  },
  {
    id: "ORD-1031",
    clientName: "Annapurna Retail",
    loadType: "Apples",
    origin: "Hyderabad",
    destination: "Kakinada",
    truckCount: 3,
    assignedTruckCount: 3,
    reportingAt: "May 02, 6:00 AM",
    deliveryDeadline: "May 03, 5:00 PM",
    baseAmount: 132000,
    chargeableExtras: 8000,
    advancePaid: 60000,
    expectedBalance: 80000,
    invoiceStatus: "Invoiced",
    assignmentStatus: "Assigned",
    orderStatus: "Invoiced",
    createdAt: "2026-05-01T09:15:00",
    source: "Direct",
    notes: "Invoice generated; verify extra distance charge before any amount edit.",
    trips: [
      {
        id: "TRP-4150",
        orderId: "ORD-1031",
        truckType: "Own truck",
        truckNumberOrContact: "TS09FD1122",
        expectedArrivalAt: "May 03, 2:30 PM",
        expenseStatus: "Diesel and tolls recorded",
        providerDueStatus: "No provider due",
        returnReadyStatus: "Return-ready from Kakinada",
        tripStatus: "Return-ready",
      },
      {
        id: "TRP-4151",
        orderId: "ORD-1031",
        truckType: "Own truck",
        truckNumberOrContact: "TS15UC2297",
        expectedArrivalAt: "May 03, 3:00 PM",
        expenseStatus: "Diesel recorded",
        providerDueStatus: "No provider due",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Completed",
      },
      {
        id: "TRP-4152",
        orderId: "ORD-1031",
        truckType: "Outsourced truck",
        truckNumberOrContact: "Sai Logistics - AP31TA8844",
        expectedArrivalAt: "May 03, 4:00 PM",
        expenseStatus: "Outsourced cost tracked",
        providerDueStatus: "Paid",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Completed",
      },
    ],
  },
  {
    id: "ORD-1024",
    clientName: "Sri Balaji Traders",
    loadType: "FMCG cartons",
    origin: "Hyderabad",
    destination: "Bengaluru",
    truckCount: 1,
    assignedTruckCount: 1,
    reportingAt: "Apr 29, 7:00 AM",
    deliveryDeadline: "Apr 30, 7:00 PM",
    baseAmount: 52000,
    chargeableExtras: 0,
    advancePaid: 52000,
    expectedBalance: 0,
    invoiceStatus: "Settled",
    assignmentStatus: "Assigned",
    orderStatus: "Settled",
    createdAt: "2026-04-29T07:00:00",
    source: "CSV",
    trips: [
      {
        id: "TRP-4012",
        orderId: "ORD-1024",
        truckType: "Own truck",
        truckNumberOrContact: "TS10AB1024",
        expectedArrivalAt: "Apr 30, 6:00 PM",
        expenseStatus: "Diesel recorded",
        providerDueStatus: "No provider due",
        returnReadyStatus: "Not return-ready",
        tripStatus: "Completed",
      },
    ],
  },
]

export const mockIntakeDrafts: IntakeDraft[] = [
  {
    id: "DRF-2201",
    source: "Quick Order",
    receivedAt: "Today, 9:20 AM",
    clientText: "Raghava Fruits",
    linkedClient: "",
    origin: "Hyderabad",
    destination: "Rajahmundry",
    truckCount: 2,
    rateAndAdvance: "Rate missing, advance Rs 20,000",
    missingFields: ["Rate amount", "Linked client"],
    duplicateRisk: "No exact duplicate found",
    status: "Missing fields",
    originalValues: [
      "Client: Raghava Fruits",
      "Route: Hyderabad to Rajahmundry",
      "Truck count: 2",
      "Advance: Rs 20,000",
    ],
    cleanedValues: [
      "Origin: Hyderabad",
      "Destination: Rajahmundry",
      "Truck count: 2",
      "Advance paid: Rs 20,000",
    ],
    notes: "Owner captured during phone call. Rate to be confirmed.",
  },
  {
    id: "DRF-2200",
    source: "Google Sheet",
    receivedAt: "Today, 8:50 AM",
    clientText: "Kaveri Foods",
    linkedClient: "Kaveri Foods",
    origin: "Medchal",
    destination: "Vijayawada",
    truckCount: 2,
    rateAndAdvance: "Rs 78,000 / no advance",
    missingFields: [],
    duplicateRisk: "Similar to ORD-1038",
    status: "Duplicate suspected",
    originalValues: [
      "Sheet row 184",
      "Client: Kaveri Foods",
      "Route: Medchal to Vijayawada",
      "Amount: 78000",
    ],
    cleanedValues: [
      "Client linked: Kaveri Foods",
      "Origin: Medchal",
      "Destination: Vijayawada",
      "Truck count: 2",
    ],
    notes: "Review before conversion because a quick order exists for same route.",
  },
  {
    id: "DRF-2197",
    source: "Google Form",
    receivedAt: "Yesterday, 5:10 PM",
    clientText: "Annapurna Retail",
    linkedClient: "Annapurna Retail",
    origin: "Hyderabad",
    destination: "Kakinada",
    truckCount: 3,
    rateAndAdvance: "Rs 1,32,000 / Rs 60,000",
    missingFields: [],
    duplicateRisk: "No duplicate risk",
    status: "Ready to create order",
    originalValues: [
      "Submitted by assistant",
      "Client: Annapurna Retail",
      "Load: Apples",
      "Rate: 132000",
    ],
    cleanedValues: [
      "Client linked: Annapurna Retail",
      "Load type: Apples",
      "Base amount: Rs 1,32,000",
      "Advance paid: Rs 60,000",
    ],
    notes: "All required fields are present.",
  },
  {
    id: "DRF-2190",
    source: "CSV",
    receivedAt: "Yesterday, 3:30 PM",
    clientText: "Bad test row",
    linkedClient: "",
    origin: "",
    destination: "",
    truckCount: 0,
    rateAndAdvance: "Could not parse",
    missingFields: ["Client", "Origin", "Destination", "Truck count", "Rate"],
    duplicateRisk: "Duplicate check unavailable",
    status: "Sync failed",
    originalValues: ["CSV row 77 failed parsing"],
    cleanedValues: ["No cleaned fields available"],
    notes: "Failed rows must not block already imported drafts.",
  },
]
